[package]
name = "code-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.3.0"
hakoniwa = { version = "1.1.5", features = ["seccomp"] }
libc = "0.2.172"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.219"
serde_json = "1.0.140"
